# Generated by Django 2.1.7 on 2019-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
