# Generated by Django 2.1.7 on 2019-04-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190406_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='county',
        ),
    ]
