# Generated by Django 2.1.7 on 2019-04-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190420_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
