education_level_choices = {
  'primary certificate':'primary certificate',
  'secondary certificate':'secondary certificate',
  'college diploma':'college diploma',
  'bachelor degree':'bachelor degree',
  'masters degree':'masters degree',
  'phd':'phd',

  }

colleges_choices = {
    'kenyatta university': 'kenyatta university',

}

country_choices = {
        'Baringo': 'Baringo',
        'Bomet': 'Bomet',
        'Bungoma': 'Bungoma',
        'Busia': 'Busia',
        'Elgeyo-Marakwet': 'Elgeyo-Marakwet',
        'Embu': 'Embu',
        'Homa Bay': 'Homa Bay',
        'Garissa': 'Garissa',
        'Isiolo': 'Isiolo',
        'Kajiado': 'Kajiado',
        'Kakamega': 'Kakamega',
        'Kericho': 'Kericho',
        'Kiambu': 'Kiambu',
        'Kilifi': 'Kilifi',
        'Kirinyaga': 'Kirinyaga',
        'Kisii': 'Kisii',
        'Kisumu': 'Kisumu',
        'Kitui': 'Kitui',
        'Laikipia': 'Laikipia',
        'Lamu': 'Lamu',
        'Machakos': 'Machakos',
        'Mandera': 'Mandera',
        'Makueni': 'Makueni',
        'Meru': 'Meru',
        'Migori': 'Migori',
        'Mombasa': 'Mombasa',
        'Muranga': 'Muranga',
        'Nairobi': 'Nairobi',
        'Nakuru': 'Nakuru',
        'Narok': 'Narok',
        'Nandi': 'Nandi',
        'Nyamira': 'Nyamira',
        'Nyandarua': 'Nyandarua',
        'Nyeri': 'Nyeri',
        'Samburu': 'Samburu',
        'Siaya': 'Siaya',
        'Taita-Taveta': 'Taita-Taveta',
        'Tana River': 'Tana River',
        'Trans Nzoia': 'Trans Nzoia',
        'Turkana': 'Turkana',
        'Tharaka-Nithi': 'Tharaka-Nithi',
        'Uasin Gishu': 'Uasin Gishu',
        'Vihiga': 'Vihiga',
        'Wajir': 'Wajir',
}

expirience_choices = {
        '1':'1',
        '2':'2',
        '3':'3',
        '4':'4',
        '5':'5',
        '6':'6',
        '7':'7',
        '8':'8',
        '9':'9',
        '10':'10',
        '11':'11',
        '12':'12',
        '13':'13',
        '14':'14',
        '15+':'15+',
}

age_choices = {
  '18':'18',
  '19':'19',
  '20':'20',
  '21':'21',
  '22':'22',
  '23':'23',
  '24':'24',
  '26':'26',
  '25':'25',
  '27':'27',
  '28':'28',
  '29':'29',
  '30':'30',
  '31':'31',
  '32':'32',
  '33':'33',
  '34':'34',
  '35':'35',
  '36':'36',
  '37':'37',
  '38':'38',
  '39':'39',
  '40':'40',
  '41':'41',
  '42':'42',
  '43':'43',
  '44':'44',
  '45':'45',
  '46':'46',
  '47':'47',
  '48':'48',
  '49':'49',
  '50':'50',
  '51':'51',
  '52':'52',
  '53':'53',
  '54':'54',
  '55':'55',
  '56':'56',
  '57':'57',
  '58':'58',
  '59':'59',
  '60':'60',
  '61':'61',
  '62':'62',
  '63':'63',
  '64':'64',
  '65':'65',



}



