# Generated by Django 2.1.7 on 2019-04-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0002_pot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testament',
            name='user',
        ),
        migrations.DeleteModel(
            name='Testament',
        ),
    ]
