# Generated by Django 2.1.7 on 2019-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0003_auto_20190411_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
